package Views;

import Controllers.MainCntl;
import java.awt.CardLayout;

public class MainUI extends javax.swing.JFrame {
    private MainCntl parentCntl;
    
    /**
     * Creates new form MainUI
     */
    public MainUI(MainCntl parentCntl) {
        initComponents();
        this.parentCntl = parentCntl;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlLeft = new javax.swing.JPanel();
        jrbEnterFood = new javax.swing.JRadioButton();
        jrbEnterMood = new javax.swing.JRadioButton();
        jrbCheckCorrelation = new javax.swing.JRadioButton();
        jrbSearchForFoods = new javax.swing.JRadioButton();
        pnlRight = new javax.swing.JPanel();
        pnlEnterFood = new javax.swing.JPanel();
        pnlEnterMood = new javax.swing.JPanel();
        pnlCheckCorrelation = new javax.swing.JPanel();
        pnlSearchForFoods = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(180);

        buttonGroup1.add(jrbEnterFood);
        jrbEnterFood.setText("Enter Food");
        jrbEnterFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnterFoodActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbEnterMood);
        jrbEnterMood.setText("Enter Mood");
        jrbEnterMood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnterMoodActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbCheckCorrelation);
        jrbCheckCorrelation.setText("Check Correlation");
        jrbCheckCorrelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCheckCorrelationActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbSearchForFoods);
        jrbSearchForFoods.setText("Search for Foods");
        jrbSearchForFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSearchForFoodsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbEnterFood)
                    .addComponent(jrbEnterMood)
                    .addComponent(jrbCheckCorrelation)
                    .addComponent(jrbSearchForFoods))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbEnterFood)
                .addGap(18, 18, 18)
                .addComponent(jrbEnterMood)
                .addGap(18, 18, 18)
                .addComponent(jrbCheckCorrelation)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchForFoods)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(pnlLeft);

        pnlRight.setLayout(new java.awt.CardLayout());

        pnlEnterFood.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout pnlEnterFoodLayout = new javax.swing.GroupLayout(pnlEnterFood);
        pnlEnterFood.setLayout(pnlEnterFoodLayout);
        pnlEnterFoodLayout.setHorizontalGroup(
            pnlEnterFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlEnterFoodLayout.setVerticalGroup(
            pnlEnterFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pnlRight.add(pnlEnterFood, "pnlEnterFood");

        pnlEnterMood.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout pnlEnterMoodLayout = new javax.swing.GroupLayout(pnlEnterMood);
        pnlEnterMood.setLayout(pnlEnterMoodLayout);
        pnlEnterMoodLayout.setHorizontalGroup(
            pnlEnterMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlEnterMoodLayout.setVerticalGroup(
            pnlEnterMoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pnlRight.add(pnlEnterMood, "pnlEnterMood");

        pnlCheckCorrelation.setBackground(new java.awt.Color(255, 51, 153));

        javax.swing.GroupLayout pnlCheckCorrelationLayout = new javax.swing.GroupLayout(pnlCheckCorrelation);
        pnlCheckCorrelation.setLayout(pnlCheckCorrelationLayout);
        pnlCheckCorrelationLayout.setHorizontalGroup(
            pnlCheckCorrelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlCheckCorrelationLayout.setVerticalGroup(
            pnlCheckCorrelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCheckCorrelation, "pnlCheckCorrelation");

        javax.swing.GroupLayout pnlSearchForFoodsLayout = new javax.swing.GroupLayout(pnlSearchForFoods);
        pnlSearchForFoods.setLayout(pnlSearchForFoodsLayout);
        pnlSearchForFoodsLayout.setHorizontalGroup(
            pnlSearchForFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        pnlSearchForFoodsLayout.setVerticalGroup(
            pnlSearchForFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pnlRight.add(pnlSearchForFoods, "pnlSearchForFoods");

        jSplitPane1.setRightComponent(pnlRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jrbEnterFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnterFoodActionPerformed
        ((CardLayout) pnlRight.getLayout()).show(pnlRight, "pnlEnterFood");
    }//GEN-LAST:event_jrbEnterFoodActionPerformed

    private void jrbEnterMoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEnterMoodActionPerformed
        ((CardLayout) pnlRight.getLayout()).show(pnlRight, "pnlEnterMood");
    }//GEN-LAST:event_jrbEnterMoodActionPerformed

    private void jrbCheckCorrelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCheckCorrelationActionPerformed
        ((CardLayout) pnlRight.getLayout()).show(pnlRight, "pnlCheckCorrelation");
    }//GEN-LAST:event_jrbCheckCorrelationActionPerformed

    private void jrbSearchForFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSearchForFoodsActionPerformed
        ((CardLayout) pnlRight.getLayout()).show(pnlRight, "pnlSearchForFoods");
    }//GEN-LAST:event_jrbSearchForFoodsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JRadioButton jrbCheckCorrelation;
    private javax.swing.JRadioButton jrbEnterFood;
    private javax.swing.JRadioButton jrbEnterMood;
    private javax.swing.JRadioButton jrbSearchForFoods;
    private javax.swing.JPanel pnlCheckCorrelation;
    private javax.swing.JPanel pnlEnterFood;
    private javax.swing.JPanel pnlEnterMood;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSearchForFoods;
    // End of variables declaration//GEN-END:variables
}
